In [2]:
import pandas as pd
import numpy as np
import regex
import os

In [3]:
# CSV file
csvfile = "/Users/javierlopez/Desktop/project-three/Allstorms.ibtracs_wmo.v03r10.csv"

In [4]:
# Read CSV file into a pandas DataFrame and view columns
csv_df = pd.read_csv(csvfile, dtype=object)
#list(df)
csv_df

,Serial_Num,Season_year,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,Wind(WMO),Pres(WMO),Center,Wind(WMO) Percentile,Pres(WMO) Percentile
0,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-11 06:00:00,NR,-8.6,79.8,0,0,reunion,-100,-100
1,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-12 06:00:00,NR,-9,78.9,0,0,reunion,-100,-100
2,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-13 06:00:00,NR,-10.4,73.2,0,0,reunion,-100,-100
3,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-14 06:00:00,NR,-12.8,69.9,0,0,reunion,-100,-100
4,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-15 06:00:00,NR,-13.9,68.9,0,0,reunion,-100,-100
5,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-16 06:00:00,NR,-15.3,67.7,0,0,reunion,-100,-100
6,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-17 06:00:00,NR,-16.5,67,0,0,reunion,-100,-100
7,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-18 06:00:00,NR,-18,67.4,0,0,reunion,-100,-100
8,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-19 06:00:00,NR,-20.6,69.8,0,0,reunion,-100,-100
9,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-20 06:00:00,NR,-22.8,72,0,0,reunion,-100,-100
10,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-21 06:00:00,NR,-27.2,75.8,0,0,reunion,-100,-100
11,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-11 06:00:00,NR,-15.2,57.4,0,0,reunion,-100,-100
12,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-12 06:00:00,NR,-15.8,56.6,0,0,reunion,-100,-100
13,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-13 06:00:00,NR,-20.3,49.9,0,0,reunion,-100,-100
14,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-14 06:00:00,NR,-26.1,46.7,0,0,reunion,-100,-100
15,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-15 06:00:00,NR,-33.2,50.4,0,0,reunion,-100,-100
16,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-16 06:00:00,NR,-34.1,51.1,0,0,reunion,-100,-100
17,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-01 06:00:00,NR,-11.4,75.5,0,0,reunion,-100,-100
18,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-02 06:00:00,NR,-11.7,74,0,0,reunion,-100,-100
19,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-03 06:00:00,NR,-14.4,64.6,0,0,reunion,-100,-100
20,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-04 06:00:00,NR,-17.6,57.6,0,0,reunion,-100,-100
21,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-05 06:00:00,NR,-24.5,56.5,0,0,reunion,-100,-100
22,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-06 06:00:00,NR,-29.6,59.9,0,0,reunion,-100,-100
23,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-07 06:00:00,NR,-34.5,69.3,0,0,reunion,-100,-100
24,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-21 06:00:00,NR,-15.1,62.5,0,0,reunion,-100,-100
25,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-22 06:00:00,NR,-15.9,61,0,0,reunion,-100,-100
26,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-23 06:00:00,NR,-16.8,59,0,0,reunion,-100,-100
27,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-24 06:00:00,NR,-17.1,57,0,0,reunion,-100,-100
28,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-25 06:00:00,NR,-17.4,54.6,0,0,reunion,-100,-100
29,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-26 06:00:00,NR,-18,52,0,0,reunion,-100,-100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200522,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 6:00,NR,-7.7,131.7,25,1003,bom,8.811,7.732
200523,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 12:00,NR,-8.5,131.4,25,1005,bom,8.811,2.686
200524,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 18:00,NR,-8.8,130.7,25,1004,bom,8.811,4.868
200525,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 0:00,NR,-10,130.1,30,1002,bom,25.808,10.454
200526,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 6:00,NR,-10.5,129.2,35,997,bom,38.771,31.234
200527,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 12:00,NR,-10.7,128.3,45,994,bom,55.849,43.442
200528,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 18:00,NR,-11,127.5,50,993,bom,60.653,46.447
200529,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 0:00,NR,-11.3,126.4,55,990,bom,69.702,52.321
200530,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 6:00,NR,-11.8,125.6,65,983,bom,78.895,68.833
200531,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 12:00,NR,-12.2,125.1,65,981,bom,78.895,70.691
200532,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 18:00,NR,-12.4,124.4,65,980,bom,78.895,71.188
200533,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 0:00,NR,-12.7,124,65,982,bom,78.895,69.502
200534,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 6:00,NR,-13,123.8,55,989,bom,69.702,58.471
200535,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 12:00,NR,-13,123.2,50,992,bom,60.653,48.176
200536,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 18:00,NR,-13.1,122.6,35,1000,bom,38.771,16.678
200537,2017114S08137,2017,4,SI,WA,FRANCES,4/30/17 0:00,NR,-13.4,122.2,35,1002,bom,38.771,10.454
200538,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 0:00,TS,13,119,0,1006,tokyo,-100,4.459
200539,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 6:00,TS,13.4,118.5,0,1006,tokyo,-100,4.459
200540,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 12:00,TS,14,117.8,0,1006,tokyo,-100,4.459
200541,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 18:00,TS,15,117.3,0,1004,tokyo,-100,8.39
200542,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 0:00,TS,16,116.8,35,1002,tokyo,0,15.757
200543,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 6:00,TS,17.1,116.6,35,1002,tokyo,0,15.757
200544,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 12:00,TS,18.1,116.2,35,1002,tokyo,0,15.757
200545,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 18:00,TS,19.3,115.6,40,998,tokyo,10.928,27.967
200546,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 0:00,TS,20.1,114.9,45,994,tokyo,22.064,39.314
200547,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 6:00,TS,21.2,114.5,50,990,tokyo,33.442,48.188
200548,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 12:00,TS,22,114.4,55,985,tokyo,43.392,55.687
200549,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 18:00,TS,22.9,114.6,45,994,tokyo,22.064,39.314
200550,2017161N13119,2017,2,WP,MM,MERBOK,6/13/17 0:00,TS,24,115,0,1002,tokyo,-100,15.757
200551,2017161N13119,2017,2,WP,MM,MERBOK,6/13/17 6:00,TS,25.5,115.7,0,1004,tokyo,-100,8.39

In [8]:
# Dropping data where the Name of the hurricane is 'UNNAMED'
#to_drop_name=['UNN']
#csv_df[~csv_df['Name'].isin(to_drop_name)]
df_1 = csv_df[~csv_df.Name.str.contains("UNN") == True]
df_1

,Serial_Num,Season_year,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,Wind(WMO),Pres(WMO),Center,Wind(WMO) Percentile,Pres(WMO) Percentile
0,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-11 06:00:00,NR,-8.6,79.8,0,0,reunion,-100,-100
1,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-12 06:00:00,NR,-9,78.9,0,0,reunion,-100,-100
2,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-13 06:00:00,NR,-10.4,73.2,0,0,reunion,-100,-100
3,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-14 06:00:00,NR,-12.8,69.9,0,0,reunion,-100,-100
4,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-15 06:00:00,NR,-13.9,68.9,0,0,reunion,-100,-100
5,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-16 06:00:00,NR,-15.3,67.7,0,0,reunion,-100,-100
6,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-17 06:00:00,NR,-16.5,67,0,0,reunion,-100,-100
7,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-18 06:00:00,NR,-18,67.4,0,0,reunion,-100,-100
8,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-19 06:00:00,NR,-20.6,69.8,0,0,reunion,-100,-100
9,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-20 06:00:00,NR,-22.8,72,0,0,reunion,-100,-100
10,1848011S09080,1848,2,SI,MM,XXXX848003,1848-01-21 06:00:00,NR,-27.2,75.8,0,0,reunion,-100,-100
11,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-11 06:00:00,NR,-15.2,57.4,0,0,reunion,-100,-100
12,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-12 06:00:00,NR,-15.8,56.6,0,0,reunion,-100,-100
13,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-13 06:00:00,NR,-20.3,49.9,0,0,reunion,-100,-100
14,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-14 06:00:00,NR,-26.1,46.7,0,0,reunion,-100,-100
15,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-15 06:00:00,NR,-33.2,50.4,0,0,reunion,-100,-100
16,1848011S15057,1848,3,SI,MM,XXXX848002,1848-01-16 06:00:00,NR,-34.1,51.1,0,0,reunion,-100,-100
17,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-01 06:00:00,NR,-11.4,75.5,0,0,reunion,-100,-100
18,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-02 06:00:00,NR,-11.7,74,0,0,reunion,-100,-100
19,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-03 06:00:00,NR,-14.4,64.6,0,0,reunion,-100,-100
20,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-04 06:00:00,NR,-17.6,57.6,0,0,reunion,-100,-100
21,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-05 06:00:00,NR,-24.5,56.5,0,0,reunion,-100,-100
22,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-06 06:00:00,NR,-29.6,59.9,0,0,reunion,-100,-100
23,1848061S12075,1848,5,SI,MM,XXXX848001,1848-03-07 06:00:00,NR,-34.5,69.3,0,0,reunion,-100,-100
24,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-21 06:00:00,NR,-15.1,62.5,0,0,reunion,-100,-100
25,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-22 06:00:00,NR,-15.9,61,0,0,reunion,-100,-100
26,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-23 06:00:00,NR,-16.8,59,0,0,reunion,-100,-100
27,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-24 06:00:00,NR,-17.1,57,0,0,reunion,-100,-100
28,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-25 06:00:00,NR,-17.4,54.6,0,0,reunion,-100,-100
29,1851080S15063,1851,2,SI,MM,XXXX851006,1851-03-26 06:00:00,NR,-18,52,0,0,reunion,-100,-100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200522,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 6:00,NR,-7.7,131.7,25,1003,bom,8.811,7.732
200523,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 12:00,NR,-8.5,131.4,25,1005,bom,8.811,2.686
200524,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 18:00,NR,-8.8,130.7,25,1004,bom,8.811,4.868
200525,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 0:00,NR,-10,130.1,30,1002,bom,25.808,10.454
200526,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 6:00,NR,-10.5,129.2,35,997,bom,38.771,31.234
200527,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 12:00,NR,-10.7,128.3,45,994,bom,55.849,43.442
200528,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 18:00,NR,-11,127.5,50,993,bom,60.653,46.447
200529,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 0:00,NR,-11.3,126.4,55,990,bom,69.702,52.321
200530,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 6:00,NR,-11.8,125.6,65,983,bom,78.895,68.833
200531,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 12:00,NR,-12.2,125.1,65,981,bom,78.895,70.691
200532,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 18:00,NR,-12.4,124.4,65,980,bom,78.895,71.188
200533,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 0:00,NR,-12.7,124,65,982,bom,78.895,69.502
200534,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 6:00,NR,-13,123.8,55,989,bom,69.702,58.471
200535,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 12:00,NR,-13,123.2,50,992,bom,60.653,48.176
200536,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 18:00,NR,-13.1,122.6,35,1000,bom,38.771,16.678
200537,2017114S08137,2017,4,SI,WA,FRANCES,4/30/17 0:00,NR,-13.4,122.2,35,1002,bom,38.771,10.454
200538,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 0:00,TS,13,119,0,1006,tokyo,-100,4.459
200539,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 6:00,TS,13.4,118.5,0,1006,tokyo,-100,4.459
200540,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 12:00,TS,14,117.8,0,1006,tokyo,-100,4.459
200541,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 18:00,TS,15,117.3,0,1004,tokyo,-100,8.39
200542,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 0:00,TS,16,116.8,35,1002,tokyo,0,15.757
200543,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 6:00,TS,17.1,116.6,35,1002,tokyo,0,15.757
200544,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 12:00,TS,18.1,116.2,35,1002,tokyo,0,15.757
200545,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 18:00,TS,19.3,115.6,40,998,tokyo,10.928,27.967
200546,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 0:00,TS,20.1,114.9,45,994,tokyo,22.064,39.314
200547,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 6:00,TS,21.2,114.5,50,990,tokyo,33.442,48.188
200548,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 12:00,TS,22,114.4,55,985,tokyo,43.392,55.687
200549,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 18:00,TS,22.9,114.6,45,994,tokyo,22.064,39.314
200550,2017161N13119,2017,2,WP,MM,MERBOK,6/13/17 0:00,TS,24,115,0,1002,tokyo,-100,15.757
200551,2017161N13119,2017,2,WP,MM,MERBOK,6/13/17 6:00,TS,25.5,115.7,0,1004,tokyo,-100,8.39

In [23]:
#Drop data prior to 1950 and reset index
df_2 = df_1.loc[df_1['Season_year'] > '1950']
df=df_2.reset_index(drop=True)
df

,Serial_Num,Season_year,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,Wind(WMO),Pres(WMO),Center,Wind(WMO) Percentile,Pres(WMO) Percentile
0,1950335S09074,1951,2,SI,MM,04S:XXXX950669,12/5/50 6:00,NR,-18.1,60.5,0,0,reunion,-100,-100
1,1950335S09074,1951,2,SI,MM,04S:XXXX950669,12/6/50 6:00,NR,-19,59.2,0,0,reunion,-100,-100
2,1950335S09074,1951,2,SI,MM,04S:XXXX950669,12/7/50 6:00,NR,-22.4,59.3,0,0,reunion,-100,-100
3,1950335S09074,1951,2,SI,MM,04S:XXXX950669,12/8/50 6:00,NR,-24,60.3,0,0,reunion,-100,-100
4,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/18/50 12:00,NR,-10,63.3,0,0,reunion,-100,-100
5,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/19/50 12:00,NR,-10.4,58.9,0,0,reunion,-100,-100
6,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/20/50 12:00,NR,-10.9,54.9,0,0,reunion,-100,-100
7,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/21/50 12:00,NR,-11.3,50.3,0,0,reunion,-100,-100
8,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/22/50 12:00,NR,-11.6,47.1,0,0,reunion,-100,-100
9,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/23/50 12:00,NR,-12.2,44.2,0,0,reunion,-100,-100
10,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/24/50 12:00,NR,-12.8,42.3,0,0,reunion,-100,-100
11,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/25/50 12:00,NR,-13.1,41.3,0,0,reunion,-100,-100
12,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/26/50 12:00,NR,-13.5,40.3,0,0,reunion,-100,-100
13,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/27/50 12:00,NR,-15.1,39.5,0,0,reunion,-100,-100
14,1950352S09063,1951,4,SI,MM,06S:XXXX950670,12/28/50 12:00,NR,-15.8,39.4,0,0,reunion,-100,-100
15,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/24/51 6:00,NR,-21.8,60,0,0,reunion,-100,-100
16,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/25/51 6:00,NR,-21.5,58.8,0,0,reunion,-100,-100
17,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/26/51 6:00,NR,-20.8,54.8,0,0,reunion,-100,-100
18,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/27/51 6:00,NR,-20.7,52.5,0,0,reunion,-100,-100
19,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/28/51 6:00,NR,-22.3,49.7,0,0,reunion,-100,-100
20,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/29/51 6:00,NR,-24.5,48.1,0,0,reunion,-100,-100
21,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/30/51 6:00,NR,-25.3,46.4,0,0,reunion,-100,-100
22,1951008S07074,1951,6,SI,MM,08S:12S:XXXX951673,1/31/51 6:00,NR,-24.6,45.8,0,0,reunion,-100,-100
23,1951011S13055,1951,7,SI,MM,10S:XXXX951671:XXXX951672,1/11/51 12:00,NR,-13.8,55,0,0,reunion,-100,-100
24,1951011S13055,1951,7,SI,MM,10S:XXXX951671:XXXX951672,1/12/51 12:00,NR,-14.1,52.7,0,0,reunion,-100,-100
25,1951011S13055,1951,7,SI,MM,10S:XXXX951671:XXXX951672,1/13/51 12:00,NR,-14.7,50,0,0,reunion,-100,-100
26,1951011S13055,1951,7,SI,MM,10S:XXXX951671:XXXX951672,1/14/51 12:00,NR,-15.4,48.1,0,0,reunion,-100,-100
27,1951011S13055,1951,7,SI,MM,10S:XXXX951671:XXXX951672,1/15/51 12:00,NR,-16.5,46.1,0,0,reunion,-100,-100
28,1951011S13055,1951,7,SI,MM,10S:XXXX951671:XXXX951672,1/16/51 12:00,NR,-17.3,45.2,0,0,reunion,-100,-100
29,1951011S13055,1951,7,SI,MM,10S:XXXX951671:XXXX951672,1/17/51 12:00,NR,-19.1,45.5,0,0,reunion,-100,-100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162761,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 6:00,NR,-7.7,131.7,25,1003,bom,8.811,7.732
162762,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 12:00,NR,-8.5,131.4,25,1005,bom,8.811,2.686
162763,2017114S08137,2017,4,SI,WA,FRANCES,4/26/17 18:00,NR,-8.8,130.7,25,1004,bom,8.811,4.868
162764,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 0:00,NR,-10,130.1,30,1002,bom,25.808,10.454
162765,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 6:00,NR,-10.5,129.2,35,997,bom,38.771,31.234
162766,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 12:00,NR,-10.7,128.3,45,994,bom,55.849,43.442
162767,2017114S08137,2017,4,SI,WA,FRANCES,4/27/17 18:00,NR,-11,127.5,50,993,bom,60.653,46.447
162768,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 0:00,NR,-11.3,126.4,55,990,bom,69.702,52.321
162769,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 6:00,NR,-11.8,125.6,65,983,bom,78.895,68.833
162770,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 12:00,NR,-12.2,125.1,65,981,bom,78.895,70.691
162771,2017114S08137,2017,4,SI,WA,FRANCES,4/28/17 18:00,NR,-12.4,124.4,65,980,bom,78.895,71.188
162772,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 0:00,NR,-12.7,124,65,982,bom,78.895,69.502
162773,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 6:00,NR,-13,123.8,55,989,bom,69.702,58.471
162774,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 12:00,NR,-13,123.2,50,992,bom,60.653,48.176
162775,2017114S08137,2017,4,SI,WA,FRANCES,4/29/17 18:00,NR,-13.1,122.6,35,1000,bom,38.771,16.678
162776,2017114S08137,2017,4,SI,WA,FRANCES,4/30/17 0:00,NR,-13.4,122.2,35,1002,bom,38.771,10.454
162777,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 0:00,TS,13,119,0,1006,tokyo,-100,4.459
162778,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 6:00,TS,13.4,118.5,0,1006,tokyo,-100,4.459
162779,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 12:00,TS,14,117.8,0,1006,tokyo,-100,4.459
162780,2017161N13119,2017,2,WP,MM,MERBOK,6/10/17 18:00,TS,15,117.3,0,1004,tokyo,-100,8.39
162781,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 0:00,TS,16,116.8,35,1002,tokyo,0,15.757
162782,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 6:00,TS,17.1,116.6,35,1002,tokyo,0,15.757
162783,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 12:00,TS,18.1,116.2,35,1002,tokyo,0,15.757
162784,2017161N13119,2017,2,WP,MM,MERBOK,6/11/17 18:00,TS,19.3,115.6,40,998,tokyo,10.928,27.967
162785,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 0:00,TS,20.1,114.9,45,994,tokyo,22.064,39.314
162786,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 6:00,TS,21.2,114.5,50,990,tokyo,33.442,48.188
162787,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 12:00,TS,22,114.4,55,985,tokyo,43.392,55.687
162788,2017161N13119,2017,2,WP,MM,MERBOK,6/12/17 18:00,TS,22.9,114.6,45,994,tokyo,22.064,39.314
162789,2017161N13119,2017,2,WP,MM,MERBOK,6/13/17 0:00,TS,24,115,0,1002,tokyo,-100,15.757
162790,2017161N13119,2017,2,WP,MM,MERBOK,6/13/17 6:00,TS,25.5,115.7,0,1004,tokyo,-100,8.39

In [5]:
# Drop the `name` column and reset the index
### BEGIN SOLUTION
df.drop(['name'], axis=1).reset_index(drop=True)
### END SOLUTION

,id,age,height_meter,weight_kg,children,occupation,academic_degree,salary,location
0,0,58,1.87,53,1,Choreographer,PhD,68,South Dakota
1,1,65,1.80,40,0,Cellarman,Bachelor,73,Delaware
2,2,32,1.80,73,1,Veterinary Surgeon,Master,69,South Dakota
3,3,61,1.79,89,0,Hawker,PhD,88,Louisiana
4,4,23,1.64,51,2,Choreographer,Bachelor,83,West Virginia
5,5,20,1.68,60,4,Medical Physicist,Bachelor,65,South Dakota
6,6,31,1.56,62,0,Weaver,Master,72,Louisiana
7,7,56,1.60,42,0,Lighthouse Keeper,Master,65,Louisiana
8,8,30,1.62,44,3,Millwright,Master,87,Louisiana
9,9,44,1.69,51,5,Medical Supplier,PhD,72,West Virginia
10,10,55,1.82,72,5,Manicurist,Bachelor,73,South Dakota
11,11,66,1.63,78,5,Window Dresser,Bachelor,90,Delaware
12,12,62,1.88,41,1,Assistant,Master,78,Alaska
13,13,35,1.53,74,5,Paramedic,Bachelor,69,Delaware
14,14,66,1.94,79,3,Genealogist,Master,75,South Dakota
15,15,23,1.87,72,2,Servant,PhD,77,South Dakota
16,16,40,1.61,46,4,Technical Liaison,Bachelor,76,Louisiana
17,17,34,1.55,78,1,Scientist,PhD,90,South Dakota
18,18,64,1.69,67,4,Market Research,PhD,79,Louisiana
19,19,25,1.86,81,4,Medical Supplier,PhD,77,South Dakota
20,20,53,1.65,48,3,Actor,PhD,74,Louisiana
21,21,41,1.75,49,4,Claims Adjustor,PhD,83,Delaware
22,22,63,1.82,76,1,Groom,Master,67,South Dakota
23,23,60,1.98,71,0,Payroll Assistant,Master,72,Alaska
24,24,23,1.96,89,2,Machine Operator,Bachelor,72,South Dakota
25,25,42,1.78,43,0,Tea Blender,Bachelor,73,West Virginia
26,26,58,1.56,80,3,Warden,Bachelor,76,Delaware
27,27,41,1.94,65,1,Undertaker,PhD,76,Delaware
28,28,60,1.66,80,5,Psychiatrist,Master,73,South Dakota
29,29,56,1.56,52,0,Planning Technician,Bachelor,85,Delaware
...,...,...,...,...,...,...,...,...,...
970,970,67,1.92,43,2,Stone Sawyer,Bachelor,86,Alaska
971,971,33,1.88,85,2,Applications Engineer,PhD,74,Delaware
972,972,60,1.95,58,1,Instructor,Master,81,Delaware
973,973,44,1.66,66,5,Engineer,Master,74,Alaska
974,974,21,1.64,38,4,Word Processing Operator,PhD,82,Louisiana
975,975,65,1.77,73,2,Metal Polisher,Bachelor,70,West Virginia
976,976,53,1.62,42,2,Plant Attendant,PhD,80,South Dakota
977,977,40,1.57,68,5,Betting Shop,Bachelor,85,West Virginia
978,978,51,1.54,63,1,Slater,PhD,75,West Virginia
979,979,44,1.67,50,5,Tunneller,Bachelor,69,Alaska
980,980,42,1.57,90,5,Storeman,Bachelor,70,Louisiana
981,981,48,1.84,83,3,Stud Hand,Bachelor,72,Delaware
982,982,37,1.93,77,2,Production Planner,Master,87,Delaware
983,983,47,1.96,59,2,Sports Administrator,Master,66,Louisiana
984,984,44,1.74,60,3,Steel Erector,Bachelor,78,Louisiana
985,985,51,1.67,74,1,Tiler,Bachelor,69,West Virginia
986,986,33,1.86,44,2,Wholesale Newspaper,PhD,73,Delaware
987,987,39,1.65,67,3,Safety Officer,Bachelor,85,South Dakota
988,988,46,1.58,68,3,Building Estimator,Master,76,South Dakota
989,989,52,1.85,65,3,Plastics Consultant,PhD,88,Delaware
990,990,21,1.83,42,5,Tea Taster,Bachelor,73,West Virginia
991,991,61,1.78,90,3,Hospital Doctor,Master,84,Louisiana
992,992,20,1.80,81,4,Purchasing Assistant,Master,67,Delaware
993,993,66,1.83,43,1,Garage Manager,PhD,83,Louisiana
994,994,31,1.57,47,3,Trichologist,Master,80,Delaware
995,995,39,1.79,50,1,Partition Erector,Master,74,South Dakota
996,996,31,1.97,65,5,Playgroup Leader,Bachelor,71,South Dakota
997,997,65,1.99,63,1,Nursery Nurse,Bachelor,89,West Virginia
998,998,33,1.77,41,0,Word Processing Operator,Master,87,Louisiana
999,999,63,1.64,39,1,Shepherd,PhD,71,West Virginia

In [8]:
# Save the cleaned data to a file called `cleaned_demographics.csv`
### BEGIN SOLUTION
clean_data = "cleaned_csv.csv"
df.to_csv(clean_data, index=False)
### END SOLUTION

In [9]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy import create_engine, MetaData
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Numeric, Text, Float

In [10]:
# Create an engine to a database file called `demographics.sqlite`
### BEGIN SOLUTION
engine = create_engine("sqlite:///demographics.sqlite")
### END SOLUTION

In [11]:
# Create a connection to the engine called `conn`
### BEGIN SOLUTION
conn = engine.connect()
### END SOLUTION

In [12]:
# Use `declarative_base` from SQLAlchemy to model the demographics table as an ORM class
# Make sure to specify types for each column
### BEGIN SOLUTION

Base = declarative_base()

class Demographics(Base):
    __tablename__ = 'demographics'

    id = Column(Integer, primary_key=True)
    age = Column(Integer)
    name = Column(Text)
    height_meter = Column(Float)
    weight_kg = Column(Float)
    children = Column(Integer)
    occupation = Column(Text)
    academic_degree = Column(Text)
    salary = Column(Integer)
    location = Column(Text)

    def __repr__(self):
        return f"id={self.id}, name={self.name}"
### END SOLUTION

SyntaxError: invalid syntax (<ipython-input-12-47e105baf1d7>, line 22)

In [13]:
# Use `create_all` to create the demographics table in the database
### BEGIN SOLUTION
Base.metadata.create_all(engine)
### END SOLUTION

NameError: name 'Base' is not defined

In [12]:
# Load the cleaned csv file into a pandas dataframe
### BEGIN SOLUTION
df_of_data_to_insert = pd.read_csv(clean_data)
### END SOLUTION

In [13]:
# Use Orient='records' to create a list of data to write
# http://pandas-docs.github.io/pandas-docs-travis/io.html#orient-options
### BEGIN SOLUTION
data = df_of_data_to_insert.to_dict(orient='records')
data[0]
### END SOLUTION

{'academic_degree': 'PhD',
 'age': 58,
 'children': 1,
 'height_meter': 1.87,
 'id': 0,
 'location': 'South Dakota',
 'name': 'Darlena Avila',
 'occupation': 'Choreographer',
 'salary': 68,
 'weight_kg': 53}

In [14]:
# Use MetaData from SQLAlchemy to reflect the tables
### BEGIN SOLUTION
metadata = MetaData(bind=engine)
metadata.reflect()
### END SOLUTION

In [15]:
# Save the reference to the `demographics` table as a variable called `table`
### BEGIN SOLUTION
table = sqlalchemy.Table('demographics', metadata, autoload=True)
### END SOLUTION

In [16]:
# Use `table.delete()` to remove any existing data.
# Note that this is a convenience function so that you can re-run the example code multiple times.
# You would not likely do this step in production.
### BEGIN SOLUTION
conn.execute(table.delete())
### END SOLUTION

In [17]:
# Use `table.insert()` to insert the data into the table
### BEGIN SOLUTION
conn.execute(table.insert(), data)
### END SOLUTION

In [18]:
# Test that the insert works by fetching the first 5 rows. 
conn.execute("select * from demographics limit 5").fetchall()

[(0, 58, 'Darlena Avila', 1.87, 53.0, 1, 'Choreographer', 'PhD', 68, 'South Dakota'),
 (1, 65, 'Yan Boyd', 1.8, 40.0, 0, 'Cellarman', 'Bachelor', 73, 'Delaware'),
 (2, 32, 'Joette Lane', 1.8, 73.0, 1, 'Veterinary Surgeon', 'Master', 69, 'South Dakota'),
 (3, 61, 'Jazmine Hunt', 1.79, 89.0, 0, 'Hawker', 'PhD', 88, 'Louisiana'),
 (4, 23, 'Remedios Gomez', 1.64, 51.0, 2, 'Choreographer', 'Bachelor', 83, 'West Virginia')]

In [19]:
# Optional - Clean Intermediate Files
os.remove(clean_data)

In [20]:
# Run this line to remove the sqlite db file to clear the cache.
# !rm demographics.sqlite

In [21]:
# !ls